chore: Pre release maintenance (#430)
* chore(nix): niv update

* chore(cargo): Add shortcut for stackablectl

* chore: Downgrade itertools

```
cargo update -p stackable-operator && make regenerate-nix
```

Trying to get rid of this problem:

```
error: hash mismatch in fixed-output derivation '/nix/store/pxj0czc4m04yswlrbzyhl1sa3ys1zksx-operator-rs-a16cafb.drv':
         specified: sha256-uP2GHSnjamcyvbV6garMP3WXVBm4vqkF3Rk6SZRjeQY=
            got:    sha256-hmqUfsBYzcnjKJRX1nftgKvXbVU1Gzsy74ZlBb/L1c0=
error: Cannot build '/nix/store/lmxxypxlm2icg5pfqa3gxbq3izhp16w3-rust_k8s-version-0.1.3.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/k45947bczra1x66f45pir1y7wi83z9zg-rust_k8s-version-0.1.3
         /nix/store/q3ib7s2bf28vy8wbwz950ah24vqn8r3b-rust_k8s-version-0.1.3-lib
error: Cannot build '/nix/store/9qb0g9pmjk8r6kjq6q7dc0m9rpv27bx9-rust_stackablectl-1.2.2.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/crbd5qa5rgh5fyi9qjryvmfy0382vw2p-rust_stackablectl-1.2.2
         /nix/store/rwfzrl7hn67xfcrv34g5fshw401iznky-rust_stackablectl-1.2.2-lib
```

* chore: Bump stackable-operator

* chore(nix): add crate2nix to the shell so we use the same version

* chore(nix): remove crate-hashes and regenerate

* chore(nix): Hard-code go version to 1.26

* chore(nix): Formatting

* Apply suggestions from code review

Co-authored-by: Techassi <git@techassi.dev>

---------

Co-authored-by: Techassi <git@techassi.dev>